### ISSUE TITLE
3. 変数と演算, 代入

### ISSUE THREAD

**Issue by tora-muscle** [tora-muscle/KURENAI_Python_Tutorial#3]
### 3.1 本章の学習の目標

- Python のプログラムでの「実行の流れ」と「情報の流れ」を理解し，順次実行 について知る.
- プログラムでの変数の命名と代入，評価について知る.
- Python の基本的なデータ型を知る.
- データ(オブジェクト)の型を調べる type() 関数とオブジェクトの所在を調べる id() 関数について知る.

**Comment by tora-muscle** [comment]
### 3.2 プログラム実行の流れと情報の流れ



> 演習 3-1 
> コンピュータのプログラムは音楽の楽譜と似た面があります.
> 音楽の楽譜も基本は前から順に音符を演奏することです(プログラムは上から下，楽譜は左から右と方 向は異なります).
> このほか，演奏箇所を切り替えたり，繰り返したりする記法があることを確認してみてください.


- リピート記号：ダル・セーニョ、ダ・カーポ、コーダなど
- 反復記号：1番カッコ、2番カッコ、ビス、テル、クアテルなど

https://composer-instruments.com/theory-sign-of-repetition/

**Comment by tora-muscle** [comment]
### 3.3 変数の名前

**▼ 語彙**

PEP8[13] とは

> PythonのPEP 8に定められた、変数などの命名規則をまとめました。(中略)
（モジュールをPythonに認識させるため、__init__.pyが必要です。また、フォルダの階層をさらに深くすることも可能）。
https://helve-blog.com/posts/python/python-pep8-naming-conventions/

**▼ 演習**

> 演習 3-2 さまざまな変数名を利用する練習.
> p2-1.py で示したプログラムについてシェル上での実行で構いませんから，変数
> 名をさまざまに代えて練習してみてください.
> - 1 行目と2行目の変数名を両方，同一のものに変更しなければならないことに注意してください.
> - 複数語をアンダースコアで接続した変数名も試すこと.
> - また，先頭に数字を用いた場合，予約語を用いた場合などにどのようなエラーが生じるかも併せて試みてください

- コミット：[0eb0ca9541a2f50a770e153c9a03b061e2b944f2](https://github.com/k-saito-en/KURENAI_Python_Tutorial/commit/0eb0ca9541a2f50a770e153c9a03b061e2b944f2)
- 先頭に数字を用いた場合どのようなエラーが生じるか
  ```
  File "/Users/**/KURENAI_Python_Tutorial/p3-2.py", line 10
      12_sum = 2 + 1
        ^
  SyntaxError: invalid decimal literal
  ```

- 予約語を用いた場合
  ```
  File "/Users/**/KURENAI_Python_Tutorial/p3-2.py", line 14
      if = 2 + 1
         ^
  SyntaxError: invalid syntax
  ```

**Comment by tora-muscle** [comment]
### 3.4 変数への代入と値の評価

**▼ 演習**

> 演習 3-3 変数の動作の説明
> 以下は 1000 円の商品の 15% 引きを計算するプログラムです.
> - このプログラムには 1 箇所誤りがあり，実行するとエラーになります.どの
> ような誤りがあるかを説明してください.
> - 誤りを修正したうえでプログラムの動作を説明してください.
> kakaku = 1000
> nebikiritsu= 15
> kakaku = Kakaku*(100-nebikiritsu)/100 print(kakaku)

- コミット：[演習3-3](https://github.com/k-saito-en/KURENAI_Python_Tutorial/commit/9960f4c15a2902ccb792bf2cb93b500f08687dce)
- 1行目のkakaku、Kakaku → nebikimae_kakaku
- ```py
   # 変数 nebikimae_kakaku に整数 1000 を格納
   nebikimae_kakaku = 1000
   # 変数 nebikiritsu に整数 15 を格納
   nebikiritsu = 15
   # 割引を適用した kakaku を計算
   kakaku = nebikimae_kakaku*(100-nebikiritsu)/100 
   # print関数で kakaku を表示
   print(kakaku)
   ```

**Comment by tora-muscle** [comment]
### 3.5 代入演算子


**▼ 疑問**

インクリメント、デクリメントは何で対応するの？

> 変数の値を1つ増減させるには以下のようなやり方がある。
> - 代入文または[累算代入文](https://docs.python.org/ja/3/reference/simple_stmts.html#augmented-assignment-statements)を使用
> - 特定の範囲で1ずつ変化する値を使用するにはrange関数を使用する
> - リストの要素と対応するインデックスを反復するにはenumerate関数を使用する
> 
>https://atmarkit.itmedia.co.jp/ait/spv/2302/21/news024.html

**Comment by tora-muscle** [comment]
### 3.6 Python で使えるデータ型

**▼ メモ**

- 整数型の桁数に上限がない = 初心者向け？
- 変数型の宣言が不要
- `type()`
    - 変数の型を確認することができる関数

**▼ 演習**

> 演習 3-4 データの型の確認
> Python シェルで以下を実行してください.
> a=1
> b = 1/2
> c = “ABC” 
> print(a) 
> print(b) 
> print(c) 
> print(type(a)) 
> print(type(b)) 
> print(type(c))

- コミット：[演習3-4](https://github.com/k-saito-en/KURENAI_Python_Tutorial/commit/e45bc71a0b017f2473fc9c8cd57d123dfbe6feaa)
- ```shell
   1
   0.5
   ABC
   <class 'int'>
   <class 'float'>
   <class 'str'>
   ```

**Comment by tora-muscle** [comment]
### 3.7 Python の変数のより正しい理解


**▼ メモ**

- `id()`
   - 変数の参照を知ることができる関数
   - 引数はオブジェクト型ならなんでもよし(9、3.14、変数a) 
      https://monozukuri-c.com/python-funclist-id/#toc4

**Comment by tora-muscle** [comment]
### 3.8 例題：平方根を求める

**▼ 演習**

> 演習 3-5 平方根を求めるプログラムの作成と実行
> 次の表のソースコードの部分を IDLE エディタで入力し, p3-1.py という名で保存
> して実行してみてください.(␣のかわりに空白を入力すること)

- [ニュートン法](https://automatic-browsing.com/平方根を数値計算で求める-ニュートン法/) で解く
  - 三角形の関係式から平方根の近似値を求める方法
- コミット : [演習3-5](https://github.com/k-saito-en/KURENAI_Python_Tutorial/commit/6c0ab14670a8f0c406a0b161fd145a7e051b8782)
- ```py
  # x の平方根を求める 
  x = 2
  #
  rnew = x
  #
  r1 = rnew
  r2 = x/r1 # 三角形の関係式から図形的に求めている
  rnew = (r1 + r2)/2 
  print(r1, rnew, r2) 
  #
  r1 = rnew
  r2 = x/r1 
  rnew = (r1 + r2)/2 
  print(r1, rnew, r2) 
  #
  r1 = rnew
  r2 = x/r1 
  rnew = (r1 + r2)/2 
  print(r1, rnew, r2) 
  #
  r1 = rnew
  r2 = x/r1 
  rnew = (r1 + r2)/2 
  print(r1, rnew, r2)

  # 出力結果
  # 2 1.5 1.0
  # 1.5 1.4166666666666665 1.3333333333333333
  # 1.4166666666666665 1.4142156862745097 1.411764705882353
  # 1.4142156862745097 1.4142135623746899 1.41421143847487
  ```

> 演習 3-6 エラーを体験する(1).
> プログラム 3-1で 4 行目の rnew を誤って rmew と綴ってみて実行し，どのよ うなエラーになるかを確かめてください.17 章「IDLE/Python でのエラーメッセー ジの読み方」も併せて参照すること.

- コミット : [演習3-6](https://github.com/k-saito-en/KURENAI_Python_Tutorial/commit/c83fc688e6db6dc428ad714ee68e90d945c4eb10)
- ```py
  # x の平方根を求める 
  x = 2
  #
  rmew = x
  #
  r1 = rnew
  r2 = x/r1 # 三角形の関係式から図形的に求めている
  rnew = (r1 + r2)/2 
  print(r1, rnew, r2) 
  #
  r1 = rnew
  r2 = x/r1 
  rnew = (r1 + r2)/2 
  print(r1, rnew, r2) 
  #
  r1 = rnew
  r2 = x/r1 
  rnew = (r1 + r2)/2 
  print(r1, rnew, r2) 
  #
  r1 = rnew
  r2 = x/r1 
  rnew = (r1 + r2)/2 
  print(r1, rnew, r2)
  
  # 出力結果
  # Traceback (most recent call last):
  #   File "/**/KURENAI_Python_Tutorial/p3-1.py", line 6, in <module>
  #     r1 = rnew
  #          ^^^^
  # NameError: name 'rnew' is not defined. Did you mean: 'rmew'?
  ```

> 演習 3-7 他の数値の平方根を求める.
> 1. p3-1.py を変更して，他の正の数値の平方根を求めてください.
> 2. また，このプログラムで 0 の平方根を求めようとすると何が生じるか確認し
> てください.単にエラーのメッセージを見るだけでなく，実際にプログラム をご自身で追いかけて(トレースすると言います)，どこで問題が生じるかを 考えてください.

1. 13の平方根を求める
  - コミット : [演習3-7-1](https://github.com/k-saito-en/KURENAI_Python_Tutorial/commit/114f36fd7d336c4de2e23dca749d471b1775d08d)
  - ```py
    # 出力結果
    # 13 7.0 1.0
    # 7.0 4.428571428571429 1.8571428571428572
    # 4.428571428571429 3.6820276497695854 2.9354838709677415
    # 3.6820276497695854 3.6063454894655185 3.5306633291614515
    ```
2. 7行目の`r2 = x/r1` の分母が０となり、エラーが生じる
  - コミット : [演習3-7-2](https://github.com/k-saito-en/KURENAI_Python_Tutorial/commit/c044372570203fab61425f209c6c344477975cf5)
  - ```py
    # 出力結果
    # Traceback (most recent call last):
    #   File "/**/KURENAI_Python_Tutorial/p3-1.py", line 7, in <module>
    #     r2 = x/r1 # 三角形の関係式から図形的に求めている
    #          ~^~~
    # ZeroDivisionError: division by zero
    ```

**▼ メモ**
- numpy
  - https://blog.kikagaku.co.jp/numpy-base#:~:text=NumPy（Numerical%20Python%20の略,ツールとなっています%E3%80%82
  - https://numpy.org/ja/

**Comment by tora-muscle** [comment]
### 3.9 割り算に注意

**▼ メモ**
- エディタ上で`r1`に対して注意メッセージが出ていた
  - `r1 > 0`が保証されていなかったため

**Comment by tora-muscle** [comment]
### 3.10 読み易い式の表記

**Comment by tora-muscle** [comment]
### 3.11 複数の変数への代入

#### ▼ メモ

- 以下のようにカンマ区切りで変数への代入を記述することができる
  ```py
  a=1
  b=2
  a, b = b, a
  print(a)
  print(b)

  # 出力
  # 2
  # 1
  ```
